default: &default
  adapter: postgresql
  encoding: unicode
  pool: 5

development:
  <<: *default
  database: torrentwatcher_development

test:
  <<: *default
  database: torrentwatcher_test

production:
  <<: *default
  database: torrentwatcher_production
  password: <%= ENV['TORRENTWATCHER_DATABASE_PASSWORD'] %>
